---

- name: configure iptables
  hosts: all
  tasks:
    - include_vars: config/vars.yaml

    - name: install iptables persistent
      apt: name=iptables-persistent state=present update_cache=true

    - name: change iptables chains to accept
      iptables:
        chain: "{{ item }}"
        jump: ACCEPT
      with_items:
           - INPUT
           - FORWARD
           - OUTPUT

    - name: flush existing firewall rules
      iptables:
        flush: true

    - name: flush iptables other rules
      command: iptables -X

    - name: allow loop back
      iptables: chain=INPUT action=append in_interface=lo jump=ACCEPT

    - name: allow established and related traffic
      iptables:
        chain: INPUT
        ctstate: RELATED,ESTABLISHED
        jump: ACCEPT

    - name: allow SSH traffic
      iptables:
        chain: INPUT
        destination_port: "{{ sshport }}"
        jump: ACCEPT
        protocol: tcp

    # - name: allow SSH traffic
    #   iptables:
    #     chain: INPUT
    #     destination_port: 22
    #     jump: ACCEPT
    #     protocol: tcp

    - name: drop other inputs
      iptables:
        chain: INPUT
        jump: DROP

    - name: save ipv4 rules
      community.general.iptables_state:
        state: saved
        path: /etc/iptables/rules.v4

    - name: save ipv6 rules
      community.general.iptables_state:
        ip_version: ipv6
        table: filter
        state: saved
        path: /etc/iptables/rules.v6

    - name: Restart ssh
      service:
        name: ssh
        state: restarted

    # - name: remove port 22 access
    #   vars:
    #     - ansible_ssh_port : "{{ sshport }}"
    #   tasks:
