- name: setup ssh
  hosts: all
  tasks:
    - include_vars: config/vars.yaml
    - name: Add a new user
      user:
        user: "{{ user_name }}"
        shell: /bin/bash
        update_password: on_create
        password: "{{ user_password | password_hash('sha512') }}"
    
    - name: Add SSH public key for user
      authorized_key:
        user: "{{ user_name }}"
        key: "{{ lookup('file', user_keyfile) }}"
        state: present
    
    - name: set ssh folder permissions
      file:
        path: /home/{{ user_name }}/.ssh
        state: directory
        mode: '0700'
        owner: "{{ user_name }}"
        group: "{{ user_name }}"

    - name: change authorized_keys permissions
      file:
        path: /home/{{ user_name }}/.ssh/authorized_keys
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: '0644'

    - name: add to sudo
      lineinfile:
        path: /etc/group
        regexp: ^(sudo.*)
        line: \1,{{ user_name }}
        backrefs: yes

    - name: Disallow root SSH access
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^PermitRootLogin"
                  line="PermitRootLogin no"
                  state=present

    - name: Disallow password authentication
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^PasswordAuthentication"
                  line="PasswordAuthentication no"
                  state=present

    - name: disallow TCP Forwarding
      lineinfile: dest=/etc/ssh/sshd_config
                  line="AllowTcpForwarding no"
                  insertafter="^#TCPKeepAlive yes"

    - name: Disallow X11 Forwarding
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^X11Forwarding yes"
                  line="X11Forwarding no"
                  state=present

    - name: Do not use PAM
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^UsePAM yes"
                  line="UsePAM no"
                  state=present

    - name: use IPv4
      lineinfile: dest=/etc/ssh/sshd_config
                  line="AddressFamily inet"
                  insertbefore=EOF

    - name: Add user to AllowUsers
      lineinfile: dest=/etc/ssh/sshd_config
                  line="AllowUsers {{ user_name }}"
                  insertbefore=EOF

    - name: change SSH port
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^#Port 22"
                  line="Port {{ sshport }}"
                  state=present

    - name: disable IPv6
      lineinfile: dest=/etc/sysctl.conf
                  line="net.ipv6.conf.all.disable_ipv6 = 1"

    - name: disable IPv6
      lineinfile: dest=/etc/sysctl.conf
                  line="net.ipv6.conf.default.disable_ipv6 = 1"

    - name: disable IPv6
      lineinfile: dest=/etc/sysctl.conf
                  line="net.ipv6.conf.lo.disable_ipv6 = 1"

    - name: reload sysctl
      command: sysctl -p
