- name: setup unattended-upgrades
  hosts: all
  tasks:
    - name: Install unattended-upgrades
      package:
        name: unattended-upgrades
        state: present

    - name: allow updates
      lineinfile: 
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        regexp: ^//(.*)-updates(.*)
        line: \1-updates\2
        backrefs: yes
        state: present

    - name: allow automatic reboots
      lineinfile: dest=/etc/apt/apt.conf.d/50unattended-upgrades
                  regexp="//Unattended-Upgrade::Automatic-Reboot \"false\";"
                  line="Unattended-Upgrade::Automatic-Reboot \"true\";"
                  state=present

    - name: remove unused kernel packages
      lineinfile: dest=/etc/apt/apt.conf.d/50unattended-upgrades
                  regexp="//Unattended-Upgrade::Remove-Unused-Kernel-Packages \"true\";"
                  line="Unattended-Upgrade::Remove-Unused-Kernel-Packages \"true\";"
                  state=present

    - name: remove new unused dependencies
      lineinfile: dest=/etc/apt/apt.conf.d/50unattended-upgrades
                  regexp="//Unattended-Upgrade::Remove-New-Unused-Dependencies \"true\";"
                  line="Unattended-Upgrade::Remove-New-Unused-Dependencies \"true\";"
                  state=present

    - name: remove unused dependencies
      lineinfile: dest=/etc/apt/apt.conf.d/50unattended-upgrades
                  regexp="//Unattended-Upgrade::Remove-Unused-Dependencies \"false\";"
                  line="Unattended-Upgrade::Remove-Unused-Dependencies \"true\";"
                  state=present

    - name: Download-Upgradeable-Packages
      lineinfile: dest=/etc/apt/apt.conf.d/10periodic
                  regexp="APT::Periodic::Download-Upgradeable-Packages \"0\";"
                  line="APT::Periodic::Download-Upgradeable-Packages \"1\";"
                  state=present

    - name: set AutocleanInterval
      lineinfile: dest=/etc/apt/apt.conf.d/10periodic
                  regexp="APT::Periodic::AutocleanInterval \"0\";"
                  line="APT::Periodic::AutocleanInterval \"7\";"
                  state=present
